language: c
sudo: true
# Use Ubuntu 16.04 Xenial (for Clang 7)
dist: xenial
# helps to use actual GCC on OSX (not Clang!) and Clang version 6
osx_image: xcode10
# build matrix with both OSes and Compilers
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
cache:
  - ccache
addons:
  # NOTE: only install Check on OSX as the version in APT is too old
  # apt:
  #   packages:
  #     - check
  homebrew:
    packages:
      - gcc5
      - check
# branches safelist
branches:
  only:
    - master
    - develop
    - /^test\/.*$/
    - /^feature\/.*$/
install:
  - wget https://github.com/libcheck/check/releases/download/0.12.0/check-0.12.0.tar.gz
  - tar -xzvf check-0.12.0.tar.gz
  - pushd check-0.12.0.tar.gz
  - cmake .
  - make -j
  - sudo make install
  - popd
before_script:
  # override $CC to use gcc-5 on OSX
  - if [ "$TRAVIS_OS_NAME" == "osx" ] && [ "$CC" == "gcc" ]; then export CC="gcc-5"; fi
  - cmake .
script:
  - make -j -k
  - ctest -V
