language: c
# Run on Ubuntu 14.04 Trusty in Travis Container
sudo: false
dist: trusty
# helps to use actual GCC on OSX (not Clang!) and Clang version 6
osx_image: xcode10
# build matrix with both OSes and Compilers
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
cache:
  - ccache
addons:
  apt:
    sources:
      # add PPAs with more up-to-date toolchains
      - ubuntu-toolchain-r-test
    packages:
      # want gcc 5.x as 4.x gives incorrect warnings
      - gcc-5
# branches safelist
branches:
  only:
    - master
    - develop
    - /^test\/.*$/
    - /^feature\/.*$/
before_install:
  # fix for homebrew failling on Travis-CI
  - if [ "$TRAVIS_OS_NAME" == "osx" ] && [ "$CC" == "gcc" ]; then brew update; fi
install:
  # install gcc-5 on OSX
  - if [ "$TRAVIS_OS_NAME" == "osx" ] && [ "$CC" == "gcc" ]; then brew install gcc5; fi
before_script:
  # override $CC to use gcc-5
  - if [ "$CC" == "gcc" ]; then export CC="gcc-5"; fi
  - cmake .
script:
  - make -j -k
  - ctest -V
