language: c
# build matrix with both OSes and Compilers
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
# exclude gcc on osx as this always points to clang
matrix:
  exclude:
  - os: osx
    compiler: gcc
cache:
  - ccache
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data
      # want gcc 6.x as 4.x gives incorrect warnings and 5.x won't install
      - gcc-6
# branches safelist
branches:
  only:
    - master
    - develop
    - /^test\/.*$/
before_script:
  - cmake .
script:
  - make -j -k
  - ctest -V
