language: c
# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty
# build matrix with both OSes and Compilers
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
# different C Standard versions - test on C99 and C11
env:
  matrix:
    - LIBSAXBOSPIRAL_C_STANDARD=99
    - LIBSAXBOSPIRAL_C_STANDARD=11
matrix:
  # exclude gcc on osx as this always points to clang
  exclude:
  - os: osx
    compiler: gcc
cache:
  - ccache
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data
# branches safelist
branches:
  only:
    - master
    - develop
    - /^test\/.*$/
install:
  # add PPAs with more up-to-date toolchains
  - if [ "$CC" = "gcc" ]; then sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test"; fi
  # install gcc-5
  - if [ "$CC" = "gcc" ]; then sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install gcc-5; fi
  # override $CC to use gcc-5
  - if [ "$CC" = "gcc" ]; then export CC="gcc-5"; fi
before_script:
  - cmake .
script:
  - make -j -k
  - ctest -V
