language: c
# build matrix with both OSes and Compilers
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
# different C Standard versions - test on C99 and C11
env:
  matrix:
    - SXBP_C_STANDARD=99
    - SXBP_C_STANDARD=11
matrix:
  include:
    # Ubuntu 14.04 Trusty support
    - os: linux
      dist: trusty
      sudo: required
    # use actual GCC on OSX (not Clang!)
    - os: osx
      osx_image: xcode8
cache:
  - ccache
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
      # add PPAs with more up-to-date toolchains
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cmake-data
      # want gcc 5.x as 4.x gives incorrect warnings
      - gcc-5
# branches safelist
branches:
  only:
    - master
    - develop
    - /^test\/.*$/
    - /^feature\/.*$/
install:
  # override $CC to use gcc-5
  - if [ "$CC" = "gcc" ]; then export CC="gcc-5"; fi
before_install:
  # install gcc-5 on OSX
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install gcc5; fi
before_script:
  - cmake .
script:
  - make -j -k
  - ctest -V
